-- =====================================================================
-- Digital Relay Berita Bahaya & Notice To Marine (NTM)
-- Migration: NTM workflow/versioning + message_documents (berita bahaya
-- document generator) + private "documents" storage bucket
-- =====================================================================

-- ---------------------------------------------------------------------
-- ntm_documents: turn this from a pure attachment-metadata table into a
-- full NTM record with its own workflow (mirrors maritime_messages'
-- state machine style) and versioning for published edits.
-- ---------------------------------------------------------------------
alter table public.ntm_documents
  add column if not exists title text not null default '',
  add column if not exists content text,
  add column if not exists area_navigasi text,
  add column if not exists effective_from timestamptz,
  add column if not exists effective_until timestamptz,
  add column if not exists status text not null default 'DRAFT'
    check (status in ('DRAFT', 'PENDING_VERIFICATION', 'VERIFIED', 'PUBLISHED', 'ARCHIVED')),
  add column if not exists verifier_id uuid references public.profiles (id) on delete set null,
  add column if not exists revision_number integer not null default 1 check (revision_number > 0),
  add column if not exists previous_version_id uuid references public.ntm_documents (id) on delete set null,
  add column if not exists updated_at timestamptz not null default now();

-- A draft NTM may not have a document attached yet (uploaded once ready,
-- possibly after verification) — relax the original NOT NULL file columns.
alter table public.ntm_documents alter column file_path drop not null;
alter table public.ntm_documents alter column file_name drop not null;

comment on column public.ntm_documents.status is
  'Workflow: DRAFT -> PENDING_VERIFICATION -> VERIFIED -> PUBLISHED; DRAFT or PUBLISHED -> ARCHIVED. Enforced by assert_ntm_transition() + the RPCs in this migration — mirrors the maritime_messages state machine.';
comment on column public.ntm_documents.previous_version_id is
  'Set when this row is a revision of a previously PUBLISHED NTM (see create_ntm_revision()) — changes to a published NTM always go through a new DRAFT revision, never a direct edit.';

create index if not exists idx_ntm_documents_status on public.ntm_documents (status);
create index if not exists idx_ntm_documents_previous_version_id on public.ntm_documents (previous_version_id);

drop trigger if exists trg_ntm_documents_set_updated_at on public.ntm_documents;
create trigger trg_ntm_documents_set_updated_at
  before update on public.ntm_documents
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------
-- message_documents: generated "berita bahaya" official documents
-- (DISTRESS/URGENCY/SAFETY/NTM), produced by the document generator
-- (src/features/document-generator/**). Separate from ntm_documents,
-- which is the /ntm module's own managed-publication workflow.
-- ---------------------------------------------------------------------
create table if not exists public.message_documents (
  id uuid primary key default gen_random_uuid(),
  message_id uuid references public.maritime_messages (id) on delete set null,
  message_number text not null,
  document_type text not null check (document_type in ('DISTRESS', 'URGENCY', 'SAFETY', 'NTM')),
  file_path text not null,
  file_name text not null,
  mime_type text not null default 'application/pdf',
  file_size bigint check (file_size >= 0),
  generated_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  archived_at timestamptz
);

comment on table public.message_documents is
  'Metadata for official PDF documents generated by the berita bahaya document generator (src/features/document-generator/**). The actual PDF bytes live in the private "documents" Supabase Storage bucket at file_path — this table never stores a public URL (see storage policies below); downloads always go through a short-lived signed URL.';

create index if not exists idx_message_documents_message_id on public.message_documents (message_id);
create index if not exists idx_message_documents_generated_by on public.message_documents (generated_by);
create index if not exists idx_message_documents_document_type on public.message_documents (document_type);

alter table public.message_documents enable row level security;

drop policy if exists message_documents_select on public.message_documents;
create policy message_documents_select
  on public.message_documents for select
  to authenticated
  using (true);

comment on policy message_documents_select on public.message_documents is
  'Every authenticated role may see generated-document metadata (matches messages.view/documents.view being open to all four roles) — this is metadata only (file name/size/type), never the file bytes or a working URL.';

drop policy if exists message_documents_insert on public.message_documents;
create policy message_documents_insert
  on public.message_documents for insert
  to authenticated
  with check (public.has_any_role(array['ADMIN', 'OPERATOR']) and generated_by = auth.uid());

drop policy if exists message_documents_archive on public.message_documents;
create policy message_documents_archive
  on public.message_documents for update
  to authenticated
  using (public.has_any_role(array['ADMIN', 'MASTER']))
  with check (public.has_any_role(array['ADMIN', 'MASTER']));

comment on policy message_documents_archive on public.message_documents is
  'Only ADMIN/MASTER may archive a generated document (set archived_at); generation itself is insert-only (see message_documents_insert).';

-- No DELETE policy: generated official documents are archived, never removed.

-- ---------------------------------------------------------------------
-- Private "documents" Storage bucket — holds both message_documents and
-- ntm_documents file bytes (path-prefixed: "berita/...", "ntm/...").
-- Deliberately NOT public: every download goes through a short-lived
-- signed URL created server-side (see src/lib/storage/documents.js),
-- never a permanent public object URL, even for published NTMs whose
-- *metadata* row is public (see ntm_documents_select_public above this
-- migration) — the requirement is specifically "no public FILE url for
-- documents with operational data".
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('documents', 'documents', false, 20971520, array['application/pdf', 'image/png', 'image/jpeg'])
on conflict (id) do update set public = false, file_size_limit = 20971520;

drop policy if exists documents_bucket_insert on storage.objects;
create policy documents_bucket_insert
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'documents' and public.has_any_role(array['ADMIN', 'MASTER', 'OPERATOR']));

drop policy if exists documents_bucket_select on storage.objects;
create policy documents_bucket_select
  on storage.objects for select
  to authenticated
  using (bucket_id = 'documents' and public.has_any_role(array['ADMIN', 'MASTER', 'OPERATOR', 'VIEWER']));

comment on policy documents_bucket_select on storage.objects is
  'Defense-in-depth only: the app never lets a browser query storage.objects directly. Real per-document authorization happens server-side (checking the RLS-protected message_documents/ntm_documents metadata row) BEFORE a signed URL is minted via the service-role client — see src/lib/storage/documents.js.';

-- No UPDATE/DELETE storage policy: generated documents are immutable once uploaded.

-- ---------------------------------------------------------------------
-- RLS: ntm_documents workflow transitions (additive/OR'd with the
-- existing ntm_documents_update policy from 20260814100400_rls_policies.sql,
-- which still allows ADMIN/MASTER to set published_at/archived_at
-- directly if ever needed operationally).
-- ---------------------------------------------------------------------

-- Edit content while still DRAFT (creator, or ADMIN). Both USING and
-- WITH CHECK require status = 'DRAFT', so this policy can never be used
-- to change status itself — only content fields, while still a draft.
drop policy if exists ntm_documents_update_draft_content on public.ntm_documents;
create policy ntm_documents_update_draft_content
  on public.ntm_documents for update
  to authenticated
  using (status = 'DRAFT' and (created_by = auth.uid() or public.has_any_role(array['ADMIN'])))
  with check (status = 'DRAFT' and (created_by = auth.uid() or public.has_any_role(array['ADMIN'])));

drop policy if exists ntm_documents_submit_transition on public.ntm_documents;
create policy ntm_documents_submit_transition
  on public.ntm_documents for update
  to authenticated
  using (status = 'DRAFT' and public.has_any_role(array['ADMIN', 'OPERATOR']))
  with check (status = 'PENDING_VERIFICATION');

drop policy if exists ntm_documents_verify_transition on public.ntm_documents;
create policy ntm_documents_verify_transition
  on public.ntm_documents for update
  to authenticated
  using (status = 'PENDING_VERIFICATION' and public.has_any_role(array['ADMIN', 'MASTER']))
  with check (status = 'VERIFIED');

drop policy if exists ntm_documents_publish_transition on public.ntm_documents;
create policy ntm_documents_publish_transition
  on public.ntm_documents for update
  to authenticated
  using (status = 'VERIFIED' and public.has_any_role(array['ADMIN', 'MASTER']))
  with check (status = 'PUBLISHED');

drop policy if exists ntm_documents_archive_transition on public.ntm_documents;
create policy ntm_documents_archive_transition
  on public.ntm_documents for update
  to authenticated
  using (
    (status = 'DRAFT' and (created_by = auth.uid() or public.has_any_role(array['ADMIN'])))
    or (status = 'PUBLISHED' and public.has_any_role(array['ADMIN', 'MASTER']))
  )
  with check (status = 'ARCHIVED');

-- Attach/replace the uploaded file while the NTM hasn't been published
-- yet. Scoped to the same status set on both sides so this policy alone
-- cannot be used to change status; the actual transition RPCs above
-- remain the only path between statuses.
drop policy if exists ntm_documents_attach_document on public.ntm_documents;
create policy ntm_documents_attach_document
  on public.ntm_documents for update
  to authenticated
  using (
    status in ('DRAFT', 'PENDING_VERIFICATION', 'VERIFIED')
    and (created_by = auth.uid() or public.has_any_role(array['ADMIN', 'MASTER']))
  )
  with check (
    status in ('DRAFT', 'PENDING_VERIFICATION', 'VERIFIED')
    and (created_by = auth.uid() or public.has_any_role(array['ADMIN', 'MASTER']))
  );

comment on policy ntm_documents_attach_document on public.ntm_documents is
  'Lets the creator (or ADMIN/MASTER) upload/replace the NTM''s file fields before it is published. Defense-in-depth alongside attach_ntm_document(): the RPC is the real gate on which columns actually get written.';

-- Tighten the insert policy (from 20260814100400_rls_policies.sql) so a
-- new row can only ever be created as DRAFT — no client can insert
-- directly into a later workflow state.
drop policy if exists ntm_documents_insert on public.ntm_documents;
create policy ntm_documents_insert
  on public.ntm_documents for insert
  to authenticated
  with check (
    public.has_any_role(array['ADMIN', 'MASTER', 'OPERATOR'])
    and created_by = auth.uid()
    and status = 'DRAFT'
  );

-- ---------------------------------------------------------------------
-- assert_ntm_transition: shared state-machine guard, mirrors
-- assert_message_transition() for maritime_messages.
-- ---------------------------------------------------------------------
create or replace function public.assert_ntm_transition(p_from text, p_to text)
returns void
language plpgsql
as $$
begin
  if not (
    (p_from = 'DRAFT' and p_to = 'PENDING_VERIFICATION')
    or (p_from = 'PENDING_VERIFICATION' and p_to = 'VERIFIED')
    or (p_from = 'VERIFIED' and p_to = 'PUBLISHED')
    or (p_from = 'DRAFT' and p_to = 'ARCHIVED')
    or (p_from = 'PUBLISHED' and p_to = 'ARCHIVED')
  ) then
    raise exception 'Transisi status NTM tidak valid: % -> %', p_from, p_to
      using errcode = '22023';
  end if;
end;
$$;

-- ---------------------------------------------------------------------
-- submit_ntm_for_verification: DRAFT -> PENDING_VERIFICATION
-- ---------------------------------------------------------------------
create or replace function public.submit_ntm_for_verification(
  p_ntm_document_id uuid,
  p_ip inet default null,
  p_user_agent text default null
)
returns public.ntm_documents
language plpgsql
as $$
declare
  v_row public.ntm_documents;
begin
  if not public.has_any_role(array['ADMIN', 'OPERATOR']) then
    raise exception 'Tidak memiliki hak akses untuk mengajukan verifikasi NTM.' using errcode = '42501';
  end if;

  select * into v_row from public.ntm_documents where id = p_ntm_document_id for update;
  if not found then
    raise exception 'NTM tidak ditemukan.' using errcode = 'P0002';
  end if;

  if not (public.has_any_role(array['ADMIN']) or v_row.created_by = auth.uid()) then
    raise exception 'Hanya pembuat NTM (atau ADMIN) yang dapat mengajukan verifikasi.' using errcode = '42501';
  end if;

  perform public.assert_ntm_transition(v_row.status, 'PENDING_VERIFICATION');

  update public.ntm_documents set status = 'PENDING_VERIFICATION' where id = p_ntm_document_id returning * into v_row;

  insert into public.activity_logs (actor_id, action, entity_type, entity_id, metadata, ip_address, user_agent)
  values (auth.uid(), 'SUBMIT_NTM_FOR_VERIFICATION', 'ntm_documents', p_ntm_document_id,
          jsonb_build_object('from', 'DRAFT', 'to', 'PENDING_VERIFICATION'), p_ip, p_user_agent);

  return v_row;
end;
$$;

-- ---------------------------------------------------------------------
-- verify_ntm: PENDING_VERIFICATION -> VERIFIED. MASTER/ADMIN only.
-- ---------------------------------------------------------------------
create or replace function public.verify_ntm(
  p_ntm_document_id uuid,
  p_ip inet default null,
  p_user_agent text default null
)
returns public.ntm_documents
language plpgsql
as $$
declare
  v_row public.ntm_documents;
begin
  if not public.has_any_role(array['ADMIN', 'MASTER']) then
    raise exception 'Hanya MASTER/ADMIN yang dapat memverifikasi NTM.' using errcode = '42501';
  end if;

  select * into v_row from public.ntm_documents where id = p_ntm_document_id for update;
  if not found then
    raise exception 'NTM tidak ditemukan.' using errcode = 'P0002';
  end if;

  perform public.assert_ntm_transition(v_row.status, 'VERIFIED');

  update public.ntm_documents
    set status = 'VERIFIED', verifier_id = auth.uid()
    where id = p_ntm_document_id
    returning * into v_row;

  insert into public.activity_logs (actor_id, action, entity_type, entity_id, metadata, ip_address, user_agent)
  values (auth.uid(), 'VERIFY_NTM', 'ntm_documents', p_ntm_document_id,
          jsonb_build_object('from', 'PENDING_VERIFICATION', 'to', 'VERIFIED'), p_ip, p_user_agent);

  return v_row;
end;
$$;

-- ---------------------------------------------------------------------
-- publish_ntm: VERIFIED -> PUBLISHED. MASTER/ADMIN only. If this row is
-- a revision (previous_version_id set), the previous PUBLISHED version
-- is atomically superseded (archived) in the same transaction, so only
-- one revision of a given ntm_number/edition is ever "live" at a time.
-- ---------------------------------------------------------------------
create or replace function public.publish_ntm(
  p_ntm_document_id uuid,
  p_ip inet default null,
  p_user_agent text default null
)
returns public.ntm_documents
language plpgsql
as $$
declare
  v_row public.ntm_documents;
begin
  if not public.has_any_role(array['ADMIN', 'MASTER']) then
    raise exception 'Hanya MASTER/ADMIN yang dapat mempublikasikan NTM.' using errcode = '42501';
  end if;

  select * into v_row from public.ntm_documents where id = p_ntm_document_id for update;
  if not found then
    raise exception 'NTM tidak ditemukan.' using errcode = 'P0002';
  end if;

  if v_row.file_path is null then
    raise exception 'NTM belum memiliki dokumen terlampir — unggah dokumen sebelum publikasi.' using errcode = '22023';
  end if;

  perform public.assert_ntm_transition(v_row.status, 'PUBLISHED');

  update public.ntm_documents
    set status = 'PUBLISHED', published_at = now()
    where id = p_ntm_document_id
    returning * into v_row;

  insert into public.activity_logs (actor_id, action, entity_type, entity_id, metadata, ip_address, user_agent)
  values (auth.uid(), 'PUBLISH_NTM', 'ntm_documents', p_ntm_document_id,
          jsonb_build_object('from', 'VERIFIED', 'to', 'PUBLISHED'), p_ip, p_user_agent);

  if v_row.previous_version_id is not null then
    update public.ntm_documents
      set status = 'ARCHIVED', archived_at = now()
      where id = v_row.previous_version_id and status = 'PUBLISHED';

    insert into public.activity_logs (actor_id, action, entity_type, entity_id, metadata, ip_address, user_agent)
    values (auth.uid(), 'ARCHIVE_NTM', 'ntm_documents', v_row.previous_version_id,
            jsonb_build_object('from', 'PUBLISHED', 'to', 'ARCHIVED', 'reason', 'superseded_by_revision', 'superseded_by', p_ntm_document_id),
            p_ip, p_user_agent);
  end if;

  return v_row;
end;
$$;

-- ---------------------------------------------------------------------
-- archive_ntm: DRAFT -> ARCHIVED (own draft, or ADMIN) / PUBLISHED ->
-- ARCHIVED (MASTER/ADMIN).
-- ---------------------------------------------------------------------
create or replace function public.archive_ntm(
  p_ntm_document_id uuid,
  p_ip inet default null,
  p_user_agent text default null
)
returns public.ntm_documents
language plpgsql
as $$
declare
  v_row public.ntm_documents;
begin
  select * into v_row from public.ntm_documents where id = p_ntm_document_id for update;
  if not found then
    raise exception 'NTM tidak ditemukan.' using errcode = 'P0002';
  end if;

  if v_row.status = 'DRAFT' then
    if not (public.has_any_role(array['ADMIN']) or v_row.created_by = auth.uid()) then
      raise exception 'Tidak memiliki hak akses untuk mengarsipkan draft NTM ini.' using errcode = '42501';
    end if;
  elsif v_row.status = 'PUBLISHED' then
    if not public.has_any_role(array['ADMIN', 'MASTER']) then
      raise exception 'Hanya MASTER/ADMIN yang dapat mengarsipkan NTM yang sudah dipublikasikan.' using errcode = '42501';
    end if;
  end if;

  perform public.assert_ntm_transition(v_row.status, 'ARCHIVED');

  update public.ntm_documents
    set status = 'ARCHIVED', archived_at = now()
    where id = p_ntm_document_id
    returning * into v_row;

  insert into public.activity_logs (actor_id, action, entity_type, entity_id, metadata, ip_address, user_agent)
  values (auth.uid(), 'ARCHIVE_NTM', 'ntm_documents', p_ntm_document_id,
          jsonb_build_object('from', v_row.status, 'to', 'ARCHIVED'), p_ip, p_user_agent);

  return v_row;
end;
$$;

-- ---------------------------------------------------------------------
-- create_ntm_revision: start a new DRAFT revision of a PUBLISHED NTM.
-- This is the ONLY sanctioned way to change a published NTM's content —
-- the original row is left untouched (still PUBLISHED) until the new
-- revision itself is published, at which point publish_ntm() supersedes
-- (archives) the original automatically.
-- ---------------------------------------------------------------------
create or replace function public.create_ntm_revision(
  p_ntm_document_id uuid,
  p_ip inet default null,
  p_user_agent text default null
)
returns public.ntm_documents
language plpgsql
as $$
declare
  v_original public.ntm_documents;
  v_new public.ntm_documents;
begin
  if not public.has_any_role(array['ADMIN', 'MASTER', 'OPERATOR']) then
    raise exception 'Tidak memiliki hak akses untuk membuat revisi NTM.' using errcode = '42501';
  end if;

  select * into v_original from public.ntm_documents where id = p_ntm_document_id;
  if not found then
    raise exception 'NTM tidak ditemukan.' using errcode = 'P0002';
  end if;

  if v_original.status <> 'PUBLISHED' then
    raise exception 'Hanya NTM yang sudah dipublikasikan yang dapat direvisi.' using errcode = '22023';
  end if;

  insert into public.ntm_documents (
    ntm_number, edition, document_type, title, content, area_navigasi,
    effective_from, effective_until, status, revision_number, previous_version_id, created_by
  )
  values (
    v_original.ntm_number, v_original.edition, v_original.document_type, v_original.title, v_original.content,
    v_original.area_navigasi, v_original.effective_from, v_original.effective_until,
    'DRAFT', v_original.revision_number + 1, v_original.id, auth.uid()
  )
  returning * into v_new;

  insert into public.activity_logs (actor_id, action, entity_type, entity_id, metadata, ip_address, user_agent)
  values (auth.uid(), 'CREATE_NTM_REVISION', 'ntm_documents', v_new.id,
          jsonb_build_object('previous_version_id', v_original.id, 'revision_number', v_new.revision_number),
          p_ip, p_user_agent);

  return v_new;
end;
$$;

-- ---------------------------------------------------------------------
-- attach_ntm_document: record an uploaded file's metadata against an
-- NTM row (the actual bytes are uploaded to Storage by the caller first
-- — see src/features/ntm/ntm-service.js).
-- ---------------------------------------------------------------------
create or replace function public.attach_ntm_document(
  p_ntm_document_id uuid,
  p_file_path text,
  p_file_name text,
  p_mime_type text,
  p_file_size bigint,
  p_ip inet default null,
  p_user_agent text default null
)
returns public.ntm_documents
language plpgsql
as $$
declare
  v_row public.ntm_documents;
begin
  select * into v_row from public.ntm_documents where id = p_ntm_document_id for update;
  if not found then
    raise exception 'NTM tidak ditemukan.' using errcode = 'P0002';
  end if;

  if v_row.status not in ('DRAFT', 'PENDING_VERIFICATION', 'VERIFIED') then
    raise exception 'Dokumen tidak dapat diunggah setelah NTM dipublikasikan atau diarsipkan — buat revisi baru.' using errcode = '22023';
  end if;

  if not (public.has_any_role(array['ADMIN', 'MASTER']) or v_row.created_by = auth.uid()) then
    raise exception 'Tidak memiliki hak akses untuk mengunggah dokumen NTM ini.' using errcode = '42501';
  end if;

  update public.ntm_documents
    set file_path = p_file_path, file_name = p_file_name, mime_type = p_mime_type, file_size = p_file_size
    where id = p_ntm_document_id
    returning * into v_row;

  insert into public.activity_logs (actor_id, action, entity_type, entity_id, metadata, ip_address, user_agent)
  values (auth.uid(), 'ATTACH_NTM_DOCUMENT', 'ntm_documents', p_ntm_document_id,
          jsonb_build_object('file_name', p_file_name, 'mime_type', p_mime_type, 'file_size', p_file_size),
          p_ip, p_user_agent);

  return v_row;
end;
$$;
